/**
 * Especificações técnicas canônicas e identificadores MLC dos modelos suportados no WebGPU Chat.
 * Focado em estabilidade, alto desempenho e execução 100% client-side na GPU local.
 */
export const MODEL_SPECS = {
	"smol-lm-3-360m": {
		lab: "Hugging Face",
		name: "SmolLM3 (360M Mobile)",
		params: "360M Parâmetros",
		vram: "~376 MB VRAM",
		desc: "Ultra-leve da família SmolLM3. Perfeito para smartphones (Galaxy M52 / Adreno), carga instantânea e mínimo consumo de VRAM.",
		primaryId: "SmolLM2-360M-Instruct-q4f32_1-MLC",
		fallbackId: "SmolLM2-360M-Instruct-q4f16_1-MLC",
		group: "📱 Mobile / Smartphones",
		badge: "📱 Ideal Celular",
	},
	"smol-lm-3-135m": {
		lab: "Hugging Face",
		name: "SmolLM3 (135M Nano)",
		params: "135M Parâmetros",
		vram: "~360 MB VRAM",
		desc: "Nano modelo para inferência instantânea com zero estresse térmico ou de memória gráfica.",
		primaryId: "SmolLM2-135M-Instruct-q0f32-MLC",
		fallbackId: "SmolLM2-135M-Instruct-q0f16-MLC",
		group: "📱 Mobile / Smartphones",
		badge: "⚡ Nano Instant",
	},
	"llama-3.2-1b": {
		lab: "Meta",
		name: "Llama 3.2 (1B)",
		params: "1.2B Parâmetros",
		vram: "~880 MB VRAM",
		desc: "Modelo compacto da Meta de altíssima fidelidade. Compreensão impecável de português, respostas diretas e zero alucinação.",
		primaryId: "Llama-3.2-1B-Instruct-q4f32_1-MLC",
		fallbackId: "Llama-3.2-1B-Instruct-q4f16_1-MLC",
		group: "⚡ Alta Fidelidade & Leveza",
		badge: "⭐ Recomendado",
	},
	"llama-3.2-3b": {
		lab: "Meta",
		name: "Llama 3.2 (3B)",
		params: "3.2B Parâmetros",
		vram: "~2.2 GB VRAM",
		desc: "Alta densidade da série Llama 3.2 para desktops e laptops com GPU moderna. Raciocínio robusto e precisão textual.",
		primaryId: "Llama-3.2-3B-Instruct-q4f32_1-MLC",
		fallbackId: "Llama-3.2-3B-Instruct-q4f16_1-MLC",
		group: "⚡ Alta Fidelidade & Leveza",
		badge: "🚀 Desktop Pro",
	},
	"gemma-4-e2b": {
		lab: "Google",
		name: "Gemma 4 (E2B)",
		params: "2.3B Efetivos",
		vram: "~1.2 GB VRAM",
		desc: "Arquitetura ultra-eficiente do Google para inferência local com respostas rápidas e estruturadas.",
		primaryId: "gemma-2-2b-it-q4f32_1-MLC",
		fallbackId: "gemma-2-2b-it-q4f16_1-MLC",
		group: "⚡ Alta Fidelidade & Leveza",
		badge: "💎 Google",
	},
	"smol-lm-3-3b": {
		lab: "Hugging Face",
		name: "SmolLM3 (3B)",
		params: "3.0B Parâmetros",
		vram: "~1.8 GB VRAM",
		desc: "Carro-chefe SmolLM3 com suporte a raciocínio em português e janela ampla de contexto.",
		primaryId: "SmolLM2-1.7B-Instruct-q4f32_1-MLC",
		fallbackId: "SmolLM2-1.7B-Instruct-q4f16_1-MLC",
		group: "⚡ Alta Fidelidade & Leveza",
		badge: "🧠 Dual Think",
	},
	"phi-4-mini": {
		lab: "Microsoft",
		name: "Phi-4-mini (3.8B)",
		params: "3.8B Parâmetros",
		vram: "~2.4 GB VRAM",
		desc: "Mais recente da Microsoft focado em raciocínio analítico denso, matemática e síntese lógica de alto nível.",
		primaryId: "Phi-4-mini-instruct-q4f32_1-MLC",
		fallbackId: "Phi-4-mini-instruct-q4f16_1-MLC",
		group: "🧠 Raciocínio Lógico & Código",
		badge: "🔬 Raciocínio Puro",
	},
	"deepseek-r1-1.5b": {
		lab: "DeepSeek",
		name: "DeepSeek R1 (1.5B)",
		params: "1.5B Parâmetros",
		vram: "~1.4 GB VRAM",
		desc: "Destilado de raciocínio lógico avançado com cadeia de pensamento visível no bloco <think>.",
		primaryId: "DeepSeek-R1-Distill-Qwen-1.5B-q4f32_1-MLC",
		fallbackId: "DeepSeek-R1-Distill-Qwen-1.5B-q4f16_1-MLC",
		group: "🧠 Raciocínio Lógico & Código",
		badge: "🔬 Reasoning",
	},
	"qwen-3.5-0.8b": {
		lab: "Alibaba",
		name: "Qwen3.5 (0.8B)",
		params: "800M Parâmetros",
		vram: "~1.6 GB VRAM",
		desc: "Gated Delta Networks, alta vazão de geração e excelente suporte multilíngue nativo.",
		primaryId: "Qwen3.5-0.8B-q4f32_1-MLC",
		fallbackId: "Qwen3.5-0.8B-q4f16_1-MLC",
		group: "🧠 Raciocínio Lógico & Código",
		badge: "⚡ Gated Delta",
	},
	"qwen-3.5-2b": {
		lab: "Alibaba",
		name: "Qwen3.5 (2B)",
		params: "2.0B Parâmetros",
		vram: "~2.4 GB VRAM",
		desc: "Arquitetura híbrida de alta fidelidade para problemas matemáticos e estruturados.",
		primaryId: "Qwen3.5-2B-q4f32_1-MLC",
		fallbackId: "Qwen3.5-2B-q4f16_1-MLC",
		group: "🧠 Raciocínio Lógico & Código",
		badge: "🔬 Delta-MoE",
	},
	"qwen-3.5-4b": {
		lab: "Alibaba",
		name: "Qwen3.5 (4B)",
		params: "4.0B Parâmetros",
		vram: "~3.8 GB VRAM",
		desc: "Modelo denso de alto poder analítico para GPUs com mais de 4GB de VRAM dedicada.",
		primaryId: "Qwen3.5-4B-q4f32_1-MLC",
		fallbackId: "Qwen3.5-4B-q4f16_1-MLC",
		group: "🧠 Raciocínio Lógico & Código",
		badge: "🚀 4B Heavy",
	},
};

export const MODEL_GROUPS = [
	{
		label: "📱 Smartphones & Dispositivos Móveis",
		options: [
			{ key: "smol-lm-3-360m", label: "SmolLM3 (360M) · ~380 MB VRAM" },
			{ key: "smol-lm-3-135m", label: "SmolLM3 (135M) · ~360 MB VRAM" },
		],
	},
	{
		label: "⚡ Alta Fidelidade & Uso Geral",
		options: [
			{ key: "llama-3.2-1b", label: "Llama 3.2 (1B) · ~880 MB VRAM ⭐" },
			{ key: "llama-3.2-3b", label: "Llama 3.2 (3B) · ~2.2 GB VRAM" },
			{ key: "gemma-4-e2b", label: "Gemma 4 (E2B) · ~1.2 GB VRAM" },
			{ key: "smol-lm-3-3b", label: "SmolLM3 (3B) · ~1.8 GB VRAM" },
		],
	},
	{
		label: "🧠 Raciocínio Analítico & Código",
		options: [
			{ key: "deepseek-r1-1.5b", label: "DeepSeek R1 (1.5B) · ~1.4 GB VRAM 🧠" },
			{ key: "phi-4-mini", label: "Phi-4-mini (3.8B) · ~2.4 GB VRAM 🔬" },
			{ key: "qwen-3.5-0.8b", label: "Qwen3.5 (0.8B) · ~1.6 GB VRAM" },
			{ key: "qwen-3.5-2b", label: "Qwen3.5 (2B) · ~2.4 GB VRAM" },
			{ key: "qwen-3.5-4b", label: "Qwen3.5 (4B) · ~3.8 GB VRAM" },
		],
	},
];

/**
 * Presets de System Prompt simplificados e robustos.
 * Evita alucinações de personas rígidas ("e eu com isso?") e laços infinitos de pensamento.
 */
export const SYSTEM_PROMPT_PRESETS = [
	{
		id: "friendly",
		name: "Amigável & Direto",
		tag: "Padrão",
		desc: "Respostas educadas, claras e objetivas em português.",
		prompt: "Você é um assistente útil e amigável. Responda em português de forma clara, direta e objetiva.",
	},
	{
		id: "tech",
		name: "Engenharia & UNIX",
		tag: "Código",
		desc: "Foco em engenharia de sistemas, C/C++, Rust, POSIX e computação perto do metal.",
		prompt: "Você é um assistente técnico especialista em engenharia de software e programação. Responda em português com precisão técnica e código limpo.",
	},
	{
		id: "free",
		name: "Sem Prompt (Livre)",
		tag: "Zero Bloat",
		desc: "Sem instruções prévias. Ideal para modelos pequenos (135M/360M) responderem direto.",
		prompt: "",
	},
	{
		id: "custom",
		name: "Personalizado",
		tag: "Custom",
		desc: "Defina suas próprias instruções de comportamento.",
		prompt: "",
	},
];
