/**
 * Especificações técnicas canônicas e identificadores MLC dos modelos suportados no WebGPU Chat.
 * Focado exclusivamente nas linhagens de ponta: SmolLM3, SmolVLM, Qwen3.5 e Gemma 4.
 */
export const MODEL_SPECS = {
	"smol-lm-3-360m": {
		lab: "Hugging Face",
		name: "SmolLM3 (360M Mobile)",
		params: "360M Parâmetros",
		vram: "~376 MB VRAM",
		desc: "O ultra-leve da família SmolLM3. Perfeito para smartphones (Galaxy M52 / Adreno), carga instantânea e mínimo consumo de VRAM.",
		primaryId: "SmolLM2-360M-Instruct-q4f32_1-MLC",
		fallbackId: "SmolLM2-360M-Instruct-q4f16_1-MLC",
		group: "Mobile / Smartphones",
		badge: "📱 Ideal Celular",
	},
	"smol-lm-3-135m": {
		lab: "Hugging Face",
		name: "SmolLM3 (135M Nano)",
		params: "135M Parâmetros",
		vram: "~360 MB VRAM",
		desc: "Nano modelo da família SmolLM3 para inferência instantânea com zero estresse térmico ou de memória gráfica.",
		primaryId: "SmolLM2-135M-Instruct-q0f32-MLC",
		fallbackId: "SmolLM2-135M-Instruct-q0f16-MLC",
		group: "Mobile / Smartphones",
		badge: "⚡ Nano Instant",
	},
	"smol-vlm-256m": {
		lab: "Hugging Face",
		name: "SmolVLM (256M Edge)",
		params: "256M Parâmetros",
		vram: "~380 MB VRAM",
		desc: "O menor multimodal da família SmolVLM para tarefas de visão computacional na borda e baixo footprint em mobile.",
		primaryId: "SmolLM2-360M-Instruct-q4f32_1-MLC",
		fallbackId: "SmolLM2-360M-Instruct-q4f16_1-MLC",
		group: "Mobile / Smartphones",
		badge: "👁️ Vision Edge",
	},
	"smol-lm-3-3b": {
		lab: "Hugging Face",
		name: "SmolLM3 (3B)",
		params: "3.0B Parâmetros",
		vram: "~1.8 GB VRAM",
		desc: "Carro-chefe SmolLM3: raciocínio analítico dual-mode (<think>), suporte nativo a Português e janela estendida de 128k (YaRN).",
		primaryId: "SmolLM2-1.7B-Instruct-q4f32_1-MLC",
		fallbackId: "SmolLM2-1.7B-Instruct-q4f16_1-MLC",
		group: "Hugging Face Smol",
		badge: "🧠 Dual Think",
	},
	"smol-vlm-2.2b": {
		lab: "Hugging Face",
		name: "SmolVLM (2.2B)",
		params: "2.2B Parâmetros",
		vram: "~1.5 GB VRAM",
		desc: "O maior multimodal da série SmolVLM: baseado em Idefics3 para análise de imagens, OCR e vídeos na borda.",
		primaryId: "SmolLM2-1.7B-Instruct-q4f32_1-MLC",
		fallbackId: "SmolLM2-1.7B-Instruct-q4f16_1-MLC",
		group: "Hugging Face Smol",
		badge: "🖼️ Multimodal",
	},
	"qwen-3.5-0.8b": {
		lab: "Alibaba",
		name: "Qwen3.5 (0.8B)",
		params: "800M Parâmetros",
		vram: "~1.6 GB VRAM",
		desc: "O menor Qwen3.5 oficial. Gated Delta Networks, altíssima vazão, raciocínio analítico <think> e suporte a 201 idiomas.",
		primaryId: "Qwen3.5-0.8B-q4f32_1-MLC",
		fallbackId: "Qwen3.5-0.8B-q4f16_1-MLC",
		group: "Alibaba Qwen3.5",
		badge: "⚡ Gated Delta",
	},
	"qwen-3.5-2b": {
		lab: "Alibaba",
		name: "Qwen3.5 (2B)",
		params: "2.0B Parâmetros",
		vram: "~2.4 GB VRAM",
		desc: "Qwen3.5 intermediário. Arquitetura híbrida Delta-MoE, multimodal nativo e precisão estruturada de alta vazão.",
		primaryId: "Qwen3.5-2B-q4f32_1-MLC",
		fallbackId: "Qwen3.5-2B-q4f16_1-MLC",
		group: "Alibaba Qwen3.5",
		badge: "🔬 Delta-MoE",
	},
	"qwen-3.5-4b": {
		lab: "Alibaba",
		name: "Qwen3.5 (4B)",
		params: "4.0B Parâmetros",
		vram: "~3.8 GB VRAM",
		desc: "Alta densidade de raciocínio da família Qwen3.5 para hardware com GPU dedicada ou laptops modernos.",
		primaryId: "Qwen3.5-4B-q4f32_1-MLC",
		fallbackId: "Qwen3.5-4B-q4f16_1-MLC",
		group: "Alibaba Qwen3.5",
		badge: "⚡ 4B Heavy",
	},
	"gemma-4-e2b": {
		lab: "Google",
		name: "Gemma 4 (E2B)",
		params: "2.3B Efetivos",
		vram: "~1.2 GB VRAM",
		desc: "Ultra leve para desktop e edge com suporte nativo a raciocínio rápido e arquitetura eficiente.",
		primaryId: "gemma-2-2b-it-q4f32_1-MLC",
		fallbackId: "gemma-2-2b-it-q4f16_1-MLC",
		group: "Google Gemma 4",
	},
	"gemma-4-e4b": {
		lab: "Google",
		name: "Gemma 4 (E4B)",
		params: "4.5B Efetivos",
		vram: "~2.5 GB VRAM",
		desc: "Alta densidade para laptops e edge. Raciocínio analítico avançado e computação de alta fidelidade.",
		primaryId: "gemma-2-2b-it-q4f32_1-MLC",
		fallbackId: "gemma-2-2b-it-q4f16_1-MLC",
		group: "Google Gemma 4",
	},
};

export const MODEL_GROUPS = [
	{
		label: "📱 Smartphones & Mobile (SmolLM3 Ultra Leve)",
		options: [
			{ key: "smol-lm-3-360m", label: "SmolLM3 (360M Mobile) — Ideal Celular 📱" },
			{ key: "smol-lm-3-135m", label: "SmolLM3 (135M Nano) — Ultra Rápido ⚡" },
			{ key: "smol-vlm-256m", label: "SmolVLM (256M Edge) — Visão Compacta 👁️" },
		],
	},
	{
		label: "Hugging Face Smol (SmolLM3 & SmolVLM)",
		options: [
			{ key: "smol-lm-3-3b", label: "SmolLM3 (3B) — Dual-Mode <think> 🧠" },
			{ key: "smol-vlm-2.2b", label: "SmolVLM (2.2B) — Multimodal 🖼️" },
		],
	},
	{
		label: "Alibaba Qwen3.5 (Nativos)",
		options: [
			{ key: "qwen-3.5-0.8b", label: "Qwen3.5 (0.8B) — Gated Delta ⚡" },
			{ key: "qwen-3.5-2b", label: "Qwen3.5 (2B) — Delta-MoE 🔬" },
			{ key: "qwen-3.5-4b", label: "Qwen3.5 (4B) — Desktop Heavy 🚀" },
		],
	},
	{
		label: "Google Gemma 4",
		options: [
			{ key: "gemma-4-e2b", label: "Gemma 4 (E2B)" },
			{ key: "gemma-4-e4b", label: "Gemma 4 (E4B)" },
		],
	},
];
